# Patricio Lugo A01707192 - Claudio López A01710963
from music21 import note, clef, chord, instrument, stream, metadata, key
import note_insertion

# Stream and stream parts creation
s = stream.Stream(id = 'stream')
s.insert(0, metadata.Metadata(title = 'Slipping Through My Fingers'))

violoncelloPart = stream.Part(id = 'violoncelloPart')
violoncelloPart.insert(0, instrument.Violoncello())
clef.bestClef(violoncelloPart, allowTreble8vb=True)

piano1 = stream.Part(id = 'piano1')
piano1.insert(0, instrument.Piano())
clef.bestClef(piano1, allowTreble8vb=True)

# Measure by measure creation
note_insertion.m01(violoncelloPart)
note_insertion.m02(violoncelloPart)
note_insertion.m03(violoncelloPart)
note_insertion.m04(violoncelloPart)
note_insertion.m05(violoncelloPart)
note_insertion.m06(violoncelloPart)
note_insertion.m07(violoncelloPart)
note_insertion.m08(violoncelloPart)
note_insertion.m09(violoncelloPart)
note_insertion.m010(violoncelloPart)
note_insertion.m011(violoncelloPart)
note_insertion.m012(violoncelloPart)
note_insertion.m013(violoncelloPart)
note_insertion.m014(violoncelloPart)
note_insertion.m015(violoncelloPart)
note_insertion.m016(violoncelloPart)
note_insertion.m017(violoncelloPart)
note_insertion.m018(violoncelloPart)
note_insertion.m019(violoncelloPart)
note_insertion.m020(violoncelloPart)

note_insertion.b_dChord(piano1, 2)
note_insertion.b_dChord(piano1)
note_insertion.c_eChord(piano1, 0.5)
note_insertion.db_fChord(piano1, 1.5)
note_insertion.silence(piano1)
note_insertion.db_fChord(piano1)
note_insertion.eb_gChord(piano1)
note_insertion.f_aChord(piano1, 2)
note_insertion.f_aChord(piano1)
note_insertion.g_bbChord(piano1, 0.5)
note_insertion.f_aChord(piano1, 1.5)
note_insertion.e_gChord(piano1, 0.5)
note_insertion.d_fChord(piano1, 1.5)
note_insertion.c_eChord(piano1)
note_insertion.silence(piano1, 2)
note_insertion.b_dChord(piano1)
note_insertion.b_dChord(piano1, 0.5)
note_insertion.c_eChord(piano1, 0.5)
note_insertion.db_fChord(piano1)
note_insertion.silence(piano1, 2)
note_insertion.d_fChord(piano1, 0.5)
note_insertion.eb_gChord(piano1, 0.5)
note_insertion.g_bbChord(piano1)
note_insertion.f_aChord(piano1)
note_insertion.d_gChord(piano1)
note_insertion.c_fChord(piano1)
note_insertion.smileChord(piano1)
note_insertion.bb_dChord(piano1, 2)
note_insertion.b_dChord(piano1)
note_insertion.c_eChord(piano1, 0.5)
note_insertion.db_fChord(piano1, 1.5)
note_insertion.silence(piano1, 2)
note_insertion.db_fChord(piano1, 0.5)
note_insertion.eb_gChord(piano1, 0.5)
note_insertion.f_aChord(piano1, 2)
note_insertion.f_aChord(piano1)
note_insertion.g_bbChord(piano1)
note_insertion.f_aChord(piano1)
note_insertion.e_gChord(piano1)
note_insertion.d_fChord(piano1)
note_insertion.c_eChord(piano1)
note_insertion.silence(piano1)
note_insertion.b_dChord(piano1, 0.5)
note_insertion.d_bbChord(piano1, 0.5)
note_insertion.d_bbChord(piano1)
note_insertion.f_aChord(piano1, 0.5)
note_insertion.f_aChord(piano1, 1.5)
note_insertion.e_gChord(piano1, 1.5)
note_insertion.e_gChord(piano1, 0.5)
note_insertion.c_fChord(piano1, 0.5)
note_insertion.b_fChord(piano1, 2.5)
note_insertion.silence(piano1, 5.5)
note_insertion.note_seq(piano1)
note_insertion.f_aChord(piano1, 0.5)
note_insertion.e_gChord(piano1)
note_insertion.e_gChord(piano1, 1.5)
note_insertion.small_seq(piano1)
note_insertion.f_aChord(piano1, 0.5)
note_insertion.f_aChord(piano1, 3)


s.insert(0, violoncelloPart)
s.insert(0, piano1)
s.write('musicxml', 'song.xml')
s.show()
