# Patricio Lugo A01707192 - Claudio López A01710963
from music21 import note, clef, chord, instrument, stream, metadata, key
import note_insertion

# Stream and stream parts creation
s = stream.Stream(id = 'stream')
s.insert(0, metadata.Metadata(title = 'Slipping Through My Fingers'))

violoncelloPart = stream.Part(id = 'violoncelloPart')
violoncelloPart.insert(0, instrument.Violoncello())
clef.bestClef(violoncelloPart, allowTreble8vb=True)

piano1 = stream.Part(id = 'piano1')
piano1.insert(0, instrument.Piano())

piano2 = stream.Part(id = 'piano2')
piano2.insert(0, instrument.Piano())

# Measure by measure creation
note_insertion.m01(violoncelloPart)
note_insertion.m02(violoncelloPart)
note_insertion.m03(violoncelloPart)
note_insertion.m04(violoncelloPart)
note_insertion.m05(violoncelloPart)
note_insertion.m06(violoncelloPart)
note_insertion.m07(violoncelloPart)
note_insertion.m08(violoncelloPart)
note_insertion.m09(violoncelloPart)
note_insertion.m010(violoncelloPart)
note_insertion.m011(violoncelloPart)
note_insertion.m012(violoncelloPart)
note_insertion.m013(violoncelloPart)
note_insertion.m014(violoncelloPart)
note_insertion.m015(violoncelloPart)
note_insertion.m016(violoncelloPart)
note_insertion.m017(violoncelloPart)
note_insertion.m018(violoncelloPart)
note_insertion.m019(violoncelloPart)
note_insertion.m020(violoncelloPart)
note_insertion.m021(violoncelloPart)
note_insertion.m022(violoncelloPart)
note_insertion.m023(violoncelloPart)
note_insertion.m024(violoncelloPart)
note_insertion.m025(violoncelloPart)
note_insertion.m026(violoncelloPart)
note_insertion.m027(violoncelloPart)
note_insertion.m028(violoncelloPart)
note_insertion.m029(violoncelloPart)
note_insertion.m030(violoncelloPart)
note_insertion.m031(violoncelloPart)
note_insertion.m032(violoncelloPart)
note_insertion.m033(violoncelloPart)
note_insertion.m034(violoncelloPart)
note_insertion.m035(violoncelloPart)
note_insertion.m036(violoncelloPart)
note_insertion.m031(violoncelloPart)

s.insert(0, violoncelloPart)
s.write('midi', 'fiesta.mid')
s.show()
